language: node_js
jobs:
  include:
    - stage: test
      node_js:
        - 14.9.0
      script:
        - npm run cover
        - cat ./build/coverage/lcov.info | npx coveralls
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        script:
          - npx semantic-release
        cleanup: 'false'
branches:
  only:
    - master
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
