language: node_js
node_js:
  - 12.9.0
cache: npm
script:
  - npm run cover
  - npx codecov
  - cat ./build/coverage/lcov.info | npx coveralls
jobs:
  include:
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
